#!/bin/sh

GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

echo
echo -e "${GREEN}Updating test $HOME for ${BLUE}$(hostname)${GREEN}...${NC}"
echo

RUNNING_GUIX_HOME=1 guix home container -L ~/.dotfiles ~/.dotfiles/chuanguix/systems/$(hostname).scm
